name: Code review
on:
  - pull_request_target
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{github.event.pull_request.head.ref}}
        repository: ${{github.event.pull_request.head.repo.full_name}}
        submodules: 'true'
        fetch-depth: 0
    - run: |
        git fetch --no-tags --prune origin
    - uses: hmarr/debug-action@v2
    - uses: adwerx/pronto-ruby@v2.9
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_EVENT_PATH: '{ "repository": { "full_name": "Saicheg/hexlet-2021" }}'
        RUBOCOP_CONFIG: ./pronto/rubocop/rubocop.yml
      with:
        runners: >-
          brakeman rails_best_practices reek rubocop
